"""empty message

Revision ID: 2238822e4f7b
Revises: 4e0658ab4ac7
Create Date: 2025-01-02 18:03:31.942936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2238822e4f7b'
down_revision = '4e0658ab4ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.alter_column('holder',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.alter_column('holder',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
