"""empty message

Revision ID: 4e0658ab4ac7
Revises: b0af3fc66994
Create Date: 2025-01-02 17:57:29.540446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0658ab4ac7'
down_revision = 'b0af3fc66994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.alter_column('holder_phone',
               existing_type=sa.SMALLINT(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.alter_column('holder_phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.SMALLINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
