"""empty message

Revision ID: 562242cf8f34
Revises: 
Create Date: 2024-12-31 05:22:47.404275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '562242cf8f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_parties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('holder_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('holder_phone', sa.SMALLINT(), nullable=False),
    sa.Column('holder_email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('time_booked', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('queued_index', sa.SMALLINT(), nullable=False),
    sa.Column('slot_id', sa.SMALLINT(), nullable=False),
    sa.Column('slot_time', postgresql.TIME(), nullable=False),
    sa.Column('slot_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['slot_date'], ['slots.date'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['slot_time'], ['slots.time'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queued_parties_holder_email'), ['holder_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_queued_parties_holder_phone'), ['holder_phone'], unique=False)

    op.create_table('slots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', postgresql.TIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('room', sa.SMALLINT(), nullable=False),
    sa.Column('booked', sa.BOOLEAN(), nullable=False),
    sa.Column('queue_length', sa.SMALLINT(), nullable=False),
    sa.Column('holder', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['holder'], ['queued_parties.holder_email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_model_pkey'),
    sa.UniqueConstraint('username', name='test_model_username_key')
    )
    op.create_table('test',
    sa.Column('name', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.UniqueConstraint('name', name='test_name_key')
    )
    op.drop_table('slots')
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queued_parties_holder_phone'))
        batch_op.drop_index(batch_op.f('ix_queued_parties_holder_email'))

    op.drop_table('queued_parties')
    # ### end Alembic commands ###
