"""empty message

Revision ID: 644fffe691ff
Revises: 11bca5c3b79b
Create Date: 2025-01-01 17:57:28.213183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644fffe691ff'
down_revision = '11bca5c3b79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passkey', sa.SMALLINT(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.drop_column('passkey')

    # ### end Alembic commands ###
