"""empty message

Revision ID: b0af3fc66994
Revises: 644fffe691ff
Create Date: 2025-01-01 18:11:32.853697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0af3fc66994'
down_revision = '644fffe691ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.alter_column('passkey',
               existing_type=sa.SMALLINT(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.alter_column('passkey',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.SMALLINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
