"""empty message

Revision ID: b4ffbcfbe7f4
Revises: 2238822e4f7b
Create Date: 2025-01-03 23:06:54.920240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ffbcfbe7f4'
down_revision = '2238822e4f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_position', sa.SMALLINT(), nullable=False))
        batch_op.drop_column('queued_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queued_parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queued_index', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('queue_position')

    # ### end Alembic commands ###
